#### 판다스 미니 프로젝트 <hr>
- 팀원: 박동규, 임동건, 차재혁, 김미래, 이송희
- 데이터파일 : 공공대학교, 사립대학교 차이점.csv
- 데이터내용 : 미국 파키스탄 공공대, 사립대별 정보

<<<분석주제: 대학교와 관련된 활동 중 졸업 후 계획에 영향을 미치는 요소가 무엇인가?>>> <hr>

[1] 모듈 로딩 및 데이터 준비 <hr>

In [1]:
import pandas as pd

FILE_NAME = '../data/공공대학교, 사립대학교 차이점.csv'


df = pd.read_csv(FILE_NAME)

## 데이터 확인
df.head(3)

,Gender,Type of Previous School,Current School Type,Major,Admission Criteria,Tuition per Semester,Difficulty Paying Tuition,\tScholarship/Financial Aid,Average GPA (CGPA),Academic Stress Level,...,Interdisciplinary Class/Project Experience,Extracurricular Participation Frequency,Career Counseling Satisfaction,Post-Graduation Plan,Commute Time,Academic Challenges,Likelihood to Recommend School,Column 20,Column 21,Column 22
0,Male,Public School (Government-funded),Public (Government-funded),"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",Below 50k,Easy (Manage to pay without much difficulty),"Yes, but I do not qualify for financial aid or...",3.1 - 3.5,High stress,...,"Yes, occasionally",Occasionally,Neutral,Seeking employment,60??90 minutes,Academic workload,"Yes, definitely",NaN,NaN,NaN
1,Female,Private School,Public (Government-funded),"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",Below 50k,Very easy (I do not face any financial difficu...,Not sure,3.1 - 3.5,High stress,...,"Yes, occasionally",Never,Neutral,"Nothing,just wanted to ruin my life.so i enrol...",More than 90 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN
2,Female,Private School,Public (Government-funded),"Engineering and Technology (e.g., Electrical, ...","Admission test scores (e.g., NAT, ECAT, univer...",50k - 100k,"Difficult (Often face financial stress, but ma...","Yes, but I do not qualify for financial aid or...",3.6 - 4.0,Moderate stress,...,"No, but I would like to",Occasionally,Neutral,Seeking employment,15??0 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN

[2] 전처리 <hr>

### [2-1] 송희 Part

In [2]:
# Tuition per Semester(한학기 등록금) 열 전처리
# 1) 값 대체: replace
# 2) 타입 변환: object --> float64
df['Tuition per Semester'].value_counts()

Tuition per Semester
50k - 100k     130
100k - 150k     77
Below 50k       65
150k - 200k     25
Above 200k       5
Name: count, dtype: int64

In [3]:
tuition_fee = {'Below 50k': 25,
               '50k - 100k': 75,
               '100k - 150k': 125,
               '150k - 200k': 175,
               'Above 200k': 225}

df['Tuition per Semester'] = df['Tuition per Semester'].replace(tuition_fee)
df['Tuition per Semester'] = df['Tuition per Semester'].astype('float64')

df['Tuition per Semester']

0       25.0
1       25.0
2       75.0
3       75.0
4       75.0
       ...
297    175.0
298     25.0
299    125.0
300    175.0
301    125.0
Name: Tuition per Semester, Length: 302, dtype: float64

In [4]:
# Difficulty Paying Tuition(등록금 납부 어려움 정도) 열 전처리
# 1) 값 대체: replace
# 2) 타입 변환: object --> float64
df['Difficulty Paying Tuition'].unique()

array(['Easy (Manage to pay without much difficulty)',
       'Very easy (I do not face any financial difficulty in paying my fees)',
       'Difficult (Often face financial stress, but manage with some support)',
       'Moderate (Occasionally experience financial strain, but manageable)',
       'Very difficult (Struggling to cover fees, require loans or assistance)'],
      dtype=object)

In [5]:
# 쉬움 ~ 어려움 = 1 ~ 5
tuition_difficulty = {"Very easy (I do not face any financial difficulty in paying my fees)": 1,
                  "Easy (Manage to pay without much difficulty)": 2,
                  "Moderate (Occasionally experience financial strain, but manageable)": 3,
                  "Difficult (Often face financial stress, but manage with some support)": 4,
                  "Very difficult (Struggling to cover fees, require loans or assistance)": 5}


df['Difficulty Paying Tuition'] = df['Difficulty Paying Tuition'].replace(tuition_difficulty)
df['Difficulty Paying Tuition'] = df['Difficulty Paying Tuition'].astype('float64')
df['Difficulty Paying Tuition']

0      2.0
1      1.0
2      4.0
3      2.0
4      4.0
      ...
297    3.0
298    1.0
299    4.0
300    3.0
301    5.0
Name: Difficulty Paying Tuition, Length: 302, dtype: float64

In [6]:
# Difficulty Paying Tuition(등록금 납부 어려움 정도) 열 전처리
# 1) 값 대체: replace
# 2) 타입 변환: object --> float64
df['\tScholarship/Financial Aid'].unique()

array(['Yes, but I do not qualify for financial aid or a scholarship.',
       'Not sure',
       'No, my university does not offer financial aid or scholarships.',
       'Yes, I am currently receiving financial aid or a scholarship.'],
      dtype=object)

In [7]:
df['\tScholarship/Financial Aid'] = df['\tScholarship/Financial Aid'].replace('Not sure',0)

df['\tScholarship/Financial Aid'].unique()

array(['Yes, but I do not qualify for financial aid or a scholarship.', 0,
       'No, my university does not offer financial aid or scholarships.',
       'Yes, I am currently receiving financial aid or a scholarship.'],
      dtype=object)

In [8]:
scholarship = {'Yes, I am currently receiving financial aid or a scholarship.': 1,
               'Yes, but I do not qualify for financial aid or a scholarship.': 0,
               'No, my university does not offer financial aid or scholarships.': 0}

df['\tScholarship/Financial Aid'] = df['\tScholarship/Financial Aid'].replace(scholarship)

### [2-2] 동건 Part

In [9]:
# Type of Previous School의 행을 수정
# 'Public School (Government-funded)'를 'Public'으로,
# 'Private School'을 'Private'으로 변경.

## public -> 1
## private -> 3

df['Type of Previous School'] = df['Type of Previous School'].replace({
        'Public School (Government-funded)': 'Public',
        'Private School': 'Private'
    })

df['Type of Previous School'] = df['Type of Previous School'].replace({
        'Public': 1,
        'Private':2,
        'Homeschooling':pd.NA
    })

In [10]:
# Current School Type의 행을 수정.
# 'Public (Government-funded)'를 'Public'으로,
# 'Not currently enrolled'을 'Not enrolled'으로 변경

df['Current School Type'] = df['Current School Type'].replace({
        'Public (Government-funded)': 'Public',
        'Not currently enrolled': 'Not enrolled'
    })

# 등록X -> 결측치
# public -> 1
# private -> 2

df['Current School Type'] = df['Current School Type'].replace({
        'Public': 1,
        'Private': 2,
        'Not enrolled':pd.NA
    })

### [2-3] 재혁 Part <hs>

In [11]:
## GPA 구간을 수치형으로 변화
gpa_map = {"1.0 - 2.0" : 1,
           "2.1 - 2.5" : 1,
		   "2.6 - 3.0" : 2,
		   "3.1 - 3.5" : 3,
		   "3.6 - 4.0" : 3}

df['Average GPA (CGPA)'] = df['Average GPA (CGPA)'].map(gpa_map)
df['Average GPA (CGPA)'] = df['Average GPA (CGPA)'].astype('float64')
df['Average GPA (CGPA)']

0      3.0
1      3.0
2      3.0
3      3.0
4      3.0
      ...
297    3.0
298    1.0
299    3.0
300    3.0
301    3.0
Name: Average GPA (CGPA), Length: 302, dtype: float64

In [12]:
## 스트레스 수준을 수치형으로 변화
stress_map = {"No stress at all" : 1,
              "Low stress" : 2,
			  "Moderate stress" : 3,
			  "High stress" : 4,
			  "Very high stress" : 5}
df['Academic Stress Level'] = df['Academic Stress Level'].map(stress_map)
df['Academic Stress Level'] = df['Academic Stress Level'].astype('float64')
df['Academic Stress Level']

0      4.0
1      4.0
2      3.0
3      3.0
4      4.0
      ...
297    5.0
298    1.0
299    3.0
300    4.0
301    5.0
Name: Academic Stress Level, Length: 302, dtype: float64

In [13]:
## 교수지원접근성을 수치형으로 변화
sup_app_map = {"Not supportive or approachable at all" : 1,
		   "Not very supportive or approachable" : 2,
		   "Neutral (Supportive at times, less approachable)" : 3,
		   "Supportive but not very approachable" : 4,
		   "Very supportive and approachable" : 5}
df['Professor Support/Accessibility'] = df['Professor Support/Accessibility'].map(sup_app_map)
df['Professor Support/Accessibility'] = df['Professor Support/Accessibility'].astype('float64')
df['Professor Support/Accessibility']

0      4.0
1      3.0
2      5.0
3      3.0
4      4.0
      ...
297    3.0
298    1.0
299    3.0
300    4.0
301    2.0
Name: Professor Support/Accessibility, Length: 302, dtype: float64

### [2-4] 동규 Part

In [14]:
## [3-1] Extracurricular Participation Frequency(교외활동참여빈도) 자료형 및 수치 변환
## ------------------------------------------
# 'Never': 0
# 'Rarely': 1
# 'Occasionally': 2
# 'Yes, occasionally': 2 (Occasionally와 동일)
# 'Frequently': 3
# 'Very frequently': 4
## ------------------------------------------
# 자료형 object -> category 변환
df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].astype('category')

# 수치 변환
for data in df['Extracurricular Participation Frequency']:
    if data == 'Never':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Never', 0)
    elif data == 'Rarely':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Rarely', 1)
    elif data == 'Occasionally':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Occasionally', 2)
    elif data == 'Yes, occasionally':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Yes, occasionally', 2)
    elif data == 'Frequently':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Frequently', 3)
    elif data == 'Very frequently':
        df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].replace('Very frequently', 4)
print(f'dataDF["Extracurricular Participation Frequency"] dtype : {df["Extracurricular Participation Frequency"].dtype}')
df.head()

dataDF["Extracurricular Participation Frequency"] dtype : category

,Gender,Type of Previous School,Current School Type,Major,Admission Criteria,Tuition per Semester,Difficulty Paying Tuition,\tScholarship/Financial Aid,Average GPA (CGPA),Academic Stress Level,...,Interdisciplinary Class/Project Experience,Extracurricular Participation Frequency,Career Counseling Satisfaction,Post-Graduation Plan,Commute Time,Academic Challenges,Likelihood to Recommend School,Column 20,Column 21,Column 22
0,Male,1,1,"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",25.0,2.0,0,3.0,4.0,...,"Yes, occasionally",2,Neutral,Seeking employment,60??90 minutes,Academic workload,"Yes, definitely",NaN,NaN,NaN
1,Female,2,1,"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",25.0,1.0,0,3.0,4.0,...,"Yes, occasionally",0,Neutral,"Nothing,just wanted to ruin my life.so i enrol...",More than 90 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN
2,Female,2,1,"Engineering and Technology (e.g., Electrical, ...","Admission test scores (e.g., NAT, ECAT, univer...",75.0,4.0,0,3.0,3.0,...,"No, but I would like to",2,Neutral,Seeking employment,15??0 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN
3,Male,2,1,"Sciences (e.g., Physics, Chemistry, Biology)","Academic performance (e.g., high school grades...",75.0,2.0,0,3.0,3.0,...,"Yes, occasionally",4,Very dissatisfied,"Planning to pursue further education (e.g., gr...",15??0 minutes,"Financial constraints, Support from peers and ...","No, I wouldn't suggest it",NaN,NaN,NaN
4,Female,1,1,Bs Artificial intelligence,University's entry test,75.0,4.0,0,3.0,4.0,...,"No, I have not had the opportunity",2,Satisfied,"Planning to pursue further education (e.g., gr...",31??0 minutes,"Academic workload, Family responsibilities","Yes, with some reservations",NaN,NaN,NaN

In [15]:
## [3-2] Post-Graduation Plan(졸업후 계획) 수치 변환
# 1. 데이터 확인
print('unique : ', df['Post-Graduation Plan'].unique())
print('nunique : ', df['Post-Graduation Plan'].nunique(), '개')
print('dtype : ', df['Post-Graduation Plan'].dtype)

## ------------------------------------------
# 1. 취업 (Seeking employment) -> 취업 또는 실무 중심
# - "Seeking employment"
# - "Web Developer"
# - "First job for experience then business"
# 2. 창업 (Entrepreneurship) -> 직접 창업 의도 or 진행 중
# - "Starting a business"
# - "Already running an agency: motioncutproductions.com"
# - "I'll start my own business"
# 3. 유학/해외 진출 (Abroad) -> 졸업 후 해외 진출
# - "Abroad"
# - "Out of Country"
# 4. 학업 지속 (Further Education) -> 대학원 진학 등
# - "Planning to pursue further education"
# - "Further education and starting a business"
# 5. 무계획/모름 (Undecided/None)
# - "Nothing"  -> 뚜렷한 계획 없음
# - "Nothing Special right now"
# - "IDK"
# - "Not sure..."
# 6. 부정적 응답/조롱 (Dismissive) -> 조롱 or 비꼼성 응답
# - "Nothing, just wanted to ruin my life. so i enrolled here"
## ------------------------------------------

unique :  ['Seeking employment'
 'Nothing,just wanted to ruin my life.so i enrolled here'
 'Planning to pursue further education (e.g., graduate or professional studies)'
 'Already running an agency: motioncutproductions.com'
 'Starting a business' 'Nothing Special right now'
 'First job for experience then business ' 'Abroad' 'Out of Country'
 'Further education and starting a business ' 'IDK'
 "Not sure, if I'll wait for my degree. I'll start my own business. "
 'Nothing ' 'Web Developer ']
nunique :  14 개
dtype :  object

In [16]:
## 2. 자료형 및 데이터 -> 범주형 변환
# 자료형 object -> category 변환
df['Post-Graduation Plan']=df['Post-Graduation Plan'].astype('category')

# 범주형 변환
# 새로운 컬럼(categorical_Post-Graduation Plan) 생성
df['categorical_PGP'] = pd.NA

df.loc[df['Post-Graduation Plan'].isin([
    "Seeking employment", "Web Developer", "First job for experience then business "
]), 'categorical_PGP'] = 'Seeking employment'

df.loc[df['Post-Graduation Plan'].isin([
    "Starting a business", "Already running an agency: motioncutproductions.com",
    "Not sure, if I'll wait for my degree. I'll start my own business. "
]), 'categorical_PGP'] = 'Entrepreneurship'

df.loc[df['Post-Graduation Plan'].isin([
    "Abroad", "Out of Country"
]), 'categorical_PGP'] = 'Abroad'

df.loc[df['Post-Graduation Plan'].isin([
    "Planning to pursue further education (e.g., graduate or professional studies)",
    "Further education and starting a business "
]), 'categorical_PGP'] = 'Further Education'

df.loc[df['Post-Graduation Plan'].isin([
    "Nothing ", "Nothing Special right now", "IDK"
]), 'categorical_PGP'] = 'Undecided/None'

df.loc[df['Post-Graduation Plan'] == "Nothing,just wanted to ruin my life.so i enrolled here", 'categorical_PGP'] = 'Dismissive'
print(f'dataDF["Post-Graduation Plan"] dtype : {df["Post-Graduation Plan"].dtype}')

dataDF["Post-Graduation Plan"] dtype : category

In [17]:
df.columns

Index(['Gender', 'Type of Previous School', 'Current School Type', 'Major',
       'Admission Criteria', 'Tuition per Semester',
       'Difficulty Paying Tuition', '\tScholarship/Financial Aid',
       'Average GPA (CGPA)', 'Academic Stress Level',
       'Professor Support/Accessibility',
       'Frequency of Professor Technology Use',
       'Interdisciplinary Class/Project Experience',
       'Extracurricular Participation Frequency',
       'Career Counseling Satisfaction', 'Post-Graduation Plan',
       'Commute Time', 'Academic Challenges', 'Likelihood to Recommend School',
       'Column 20', 'Column 21', 'Column 22', 'categorical_PGP'],
      dtype='object')

In [18]:
## 3. 딕셔너리 매핑 후 한번에 숫자로 변환
pgp_map = {
    "Seeking employment": 1,
    "Web Developer ": 2,
    "First job for experience then business ": 3,
    "Starting a business": 4,
    "Already running an agency: motioncutproductions.com": 5,
    "Not sure, if I'll wait for my degree. I'll start my own business. ": 6,
    "Abroad": 7,
    "Out of Country": 8,
    "Planning to pursue further education (e.g., graduate or professional studies)": 9,
    "Further education and starting a business ": 10,
    "Nothing ": 11,
    "Nothing Special right now": 12,
    "IDK": 13,
    "Not sure...": 14,
    "Nothing,just wanted to ruin my life.so i enrolled here": 15
}

# 매핑 적용
df['Post-Graduation Plan'] = df['Post-Graduation Plan'].replace(pgp_map)

df['Post-Graduation Plan']

df.head(3)

,Gender,Type of Previous School,Current School Type,Major,Admission Criteria,Tuition per Semester,Difficulty Paying Tuition,\tScholarship/Financial Aid,Average GPA (CGPA),Academic Stress Level,...,Extracurricular Participation Frequency,Career Counseling Satisfaction,Post-Graduation Plan,Commute Time,Academic Challenges,Likelihood to Recommend School,Column 20,Column 21,Column 22,categorical_PGP
0,Male,1,1,"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",25.0,2.0,0,3.0,4.0,...,2,Neutral,1,60??90 minutes,Academic workload,"Yes, definitely",NaN,NaN,NaN,Seeking employment
1,Female,2,1,"Engineering and Technology (e.g., Electrical, ...","Academic performance (e.g., high school grades...",25.0,1.0,0,3.0,4.0,...,0,Neutral,15,More than 90 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN,Dismissive
2,Female,2,1,"Engineering and Technology (e.g., Electrical, ...","Admission test scores (e.g., NAT, ECAT, univer...",75.0,4.0,0,3.0,3.0,...,2,Neutral,1,15??0 minutes,Academic workload,"No, I wouldn't suggest it",NaN,NaN,NaN,Seeking employment

In [19]:
## ------------------------------------------
# 1. 취업 (Seeking employment) -> 취업 또는 실무 중심
# - "Seeking employment"
# - "Web Developer"
# - "First job for experience then business"
# 2. 창업 (Entrepreneurship) -> 직접 창업 의도 or 진행 중
# - "Starting a business"
# - "Already running an agency: motioncutproductions.com"
# - "I'll start my own business"
# 3. 유학/해외 진출 (Abroad) -> 졸업 후 해외 진출
# - "Abroad"
# - "Out of Country"
# 4. 학업 지속 (Further Education) -> 대학원 진학 등
# - "Planning to pursue further education"
# - "Further education and starting a business"
# 5. 무계획/모름 (Undecided/None)
# - "Nothing"  -> 뚜렷한 계획 없음
# - "Nothing Special right now"
# - "IDK"
# - "Not sure..."
# 6. 부정적 응답/조롱 (Dismissive) -> 조롱 or 비꼼성 응답
# - "Nothing, just wanted to ruin my life. so i enrolled here"
## ------------------------------------------

## 3. 딕셔너리 매핑 후 한번에 숫자로 변환
pgp_map = {
    "Seeking employment": 1,
    "Entrepreneurship": 2,
    "Abroad":3,
    "Further Education":4,
    "Undecided/None":5,
    "Dismissive":pd.NA
}

# 매핑 적용
df['categorical_PGP'] = df['categorical_PGP'].replace(pgp_map)
df['categorical_PGP']

0         1
1      <NA>
2         1
3         4
4         4
       ...
297       1
298       4
299       4
300       1
301       4
Name: categorical_PGP, Length: 302, dtype: object

### [2-5] 미래 Part

In [20]:
# 진로 상담 만족도
satisfaction = {
    "Very dissatisfied": 1,
    "Dissatisfied": 2,
    "Neutral": 3,
    "Satisfied": 4,
    "Very satisfied": 5
}

# 공백 제거 후 매핑
df['Career Counseling Satisfaction'] = df['Career Counseling Satisfaction'].replace(satisfaction)
df['Career Counseling Satisfaction'] = df['Career Counseling Satisfaction'].astype('float64')

df['Career Counseling Satisfaction']

0      3.0
1      3.0
2      3.0
3      1.0
4      4.0
      ...
297    5.0
298    1.0
299    3.0
300    4.0
301    4.0
Name: Career Counseling Satisfaction, Length: 302, dtype: float64

In [21]:
# 교수 기술 활용 빈도

frequency_tech = {
    "Very frequently (Almost every class)": 4,
    "Frequently (Most classes)": 1,
    "Occasionally (Some classes)": 3,
    "Rarely (Seldom used)": 2,
    "Never (Not used at all)": 5
}

df['Frequency of Professor Technology Use'] = df['Frequency of Professor Technology Use'].replace(frequency_tech)
df['Frequency of Professor Technology Use'] = df['Frequency of Professor Technology Use'].astype('float64')

df['Frequency of Professor Technology Use']

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
297    4.0
298    5.0
299    3.0
300    4.0
301    4.0
Name: Frequency of Professor Technology Use, Length: 302, dtype: float64

In [22]:
## 불필요한 열삭제

df.drop(['Column 20', 'Column 21', 'Column 22', 'Academic Challenges', 'Commute Time', 'Gender', 'Admission Criteria',
         'Interdisciplinary Class/Project Experience', 'Major', 'Likelihood to Recommend School', 'categorical_PGP',
         'Post-Graduation Plan'], axis=1, inplace=True)

df.head()

,Type of Previous School,Current School Type,Tuition per Semester,Difficulty Paying Tuition,\tScholarship/Financial Aid,Average GPA (CGPA),Academic Stress Level,Professor Support/Accessibility,Frequency of Professor Technology Use,Extracurricular Participation Frequency,Career Counseling Satisfaction
0,1,1,25.0,2.0,0,3.0,4.0,4.0,1.0,2,3.0
1,2,1,25.0,1.0,0,3.0,4.0,3.0,1.0,0,3.0
2,2,1,75.0,4.0,0,3.0,3.0,5.0,1.0,2,3.0
3,2,1,75.0,2.0,0,3.0,3.0,3.0,1.0,4,1.0
4,1,1,75.0,4.0,0,3.0,4.0,4.0,1.0,2,4.0

In [23]:
## 결측치 삭제 필요 요소
df.isna().sum()

df.dropna(inplace=True)

df.isna().sum()

Type of Previous School                    0
Current School Type                        0
Tuition per Semester                       0
Difficulty Paying Tuition                  0
\tScholarship/Financial Aid                0
Average GPA (CGPA)                         0
Academic Stress Level                      0
Professor Support/Accessibility            0
Frequency of Professor Technology Use      0
Extracurricular Participation Frequency    0
Career Counseling Satisfaction             0
dtype: int64

In [24]:
## 타입 전환
df['Type of Previous School']=df['Type of Previous School'].astype('float')
df['Current School Type']=df['Current School Type'].astype('float')
df['\tScholarship/Financial Aid']=df['\tScholarship/Financial Aid'].astype('float')
df['Extracurricular Participation Frequency']=df['Extracurricular Participation Frequency'].astype('float')

df

,Type of Previous School,Current School Type,Tuition per Semester,Difficulty Paying Tuition,\tScholarship/Financial Aid,Average GPA (CGPA),Academic Stress Level,Professor Support/Accessibility,Frequency of Professor Technology Use,Extracurricular Participation Frequency,Career Counseling Satisfaction
0,1.0,1.0,25.0,2.0,0.0,3.0,4.0,4.0,1.0,2.0,3.0
1,2.0,1.0,25.0,1.0,0.0,3.0,4.0,3.0,1.0,0.0,3.0
2,2.0,1.0,75.0,4.0,0.0,3.0,3.0,5.0,1.0,2.0,3.0
3,2.0,1.0,75.0,2.0,0.0,3.0,3.0,3.0,1.0,4.0,1.0
4,1.0,1.0,75.0,4.0,0.0,3.0,4.0,4.0,1.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...
296,1.0,1.0,125.0,1.0,1.0,3.0,3.0,3.0,1.0,2.0,4.0
297,1.0,2.0,175.0,3.0,0.0,3.0,5.0,3.0,4.0,4.0,5.0
299,2.0,2.0,125.0,4.0,0.0,3.0,3.0,3.0,3.0,1.0,3.0
300,1.0,2.0,175.0,3.0,0.0,3.0,4.0,4.0,4.0,1.0,4.0
301,1.0,2.0,125.0,5.0,0.0,3.0,5.0,2.0,4.0,3.0,4.0

### [3] 상관계수 분석

In [25]:
# 성적 1.0~2.5

mask1=df['Average GPA (CGPA)']==1
round(df[mask1].describe().loc['mean'], 1)

Type of Previous School                      1.8
Current School Type                          1.6
Tuition per Semester                       100.0
Difficulty Paying Tuition                    3.4
\tScholarship/Financial Aid                  0.2
Average GPA (CGPA)                           1.0
Academic Stress Level                        3.8
Professor Support/Accessibility              3.4
Frequency of Professor Technology Use        2.9
Extracurricular Participation Frequency      1.6
Career Counseling Satisfaction               3.0
Name: mean, dtype: float64

In [26]:
# 성적 3.1~4.0

mask1=df['Average GPA (CGPA)']==3
round(df[mask1].describe().loc['mean'],1)

Type of Previous School                     1.5
Current School Type                         1.4
Tuition per Semester                       87.9
Difficulty Paying Tuition                   3.5
\tScholarship/Financial Aid                 0.2
Average GPA (CGPA)                          3.0
Academic Stress Level                       3.6
Professor Support/Accessibility             3.9
Frequency of Professor Technology Use       2.3
Extracurricular Participation Frequency     1.7
Career Counseling Satisfaction              3.1
Name: mean, dtype: float64

In [30]:
# [3-2] 창업 학생 상관관계 요인분석
df[df['categorical_PGP']==2].describe()

KeyError: 'categorical_PGP'

In [ ]:
# [3-3] 창업 학생 상관관계 요인분석
df[df['categorical_PGP']==2].describe()

Type of Previous School                    0.221717
Current School Type                        0.044239
Tuition per Semester                       0.020936
Difficulty Paying Tuition                 -0.207752
\tScholarship/Financial Aid                0.082291
Average GPA (CGPA)                        -0.026187
Academic Stress Level                     -0.055178
Professor Support/Accessibility           -0.074588
Frequency of Professor Technology Use     -0.014524
Extracurricular Participation Frequency    0.121730
Career Counseling Satisfaction             0.098486
Post-Graduation Plan                       0.997177
categorical_PGP                            1.000000
Name: categorical_PGP, dtype: float64

In [ ]:
# [3-4] 학업지속 학생 상관관계 요인분석
mask = (df['categorical_PGP']==4)
df[mask]
df.corr().loc['categorical_PGP']

Type of Previous School                    0.221717
Current School Type                        0.044239
Tuition per Semester                       0.020936
Difficulty Paying Tuition                 -0.207752
\tScholarship/Financial Aid                0.082291
Average GPA (CGPA)                        -0.026187
Academic Stress Level                     -0.055178
Professor Support/Accessibility           -0.074588
Frequency of Professor Technology Use     -0.014524
Extracurricular Participation Frequency    0.121730
Career Counseling Satisfaction             0.098486
Post-Graduation Plan                       0.997177
categorical_PGP                            1.000000
Name: categorical_PGP, dtype: float64

In [ ]:
# [3-5] 무계획 학생 상관관계 요인분석
mask = (df['categorical_PGP']==5)
df[mask]
df.corr().loc['categorical_PGP']

Type of Previous School                    0.221717
Current School Type                        0.044239
Tuition per Semester                       0.020936
Difficulty Paying Tuition                 -0.207752
\tScholarship/Financial Aid                0.082291
Average GPA (CGPA)                        -0.026187
Academic Stress Level                     -0.055178
Professor Support/Accessibility           -0.074588
Frequency of Professor Technology Use     -0.014524
Extracurricular Participation Frequency    0.121730
Career Counseling Satisfaction             0.098486
Post-Graduation Plan                       0.997177
categorical_PGP                            1.000000
Name: categorical_PGP, dtype: float64